In [5]:
%matplotlib inline

In [6]:
from matplotlib import pyplot as plt
import numpy as np
from ipywidgets import interact
from IPython.display import clear_output

np.set_printoptions(suppress=True)

import lstm

In [9]:
X_DIM = 2
H_DIM = 3
Y_DIM = 1
TIME_STEPS = 2
TS = range(TIME_STEPS)

net = lstm.LSTMNetwork(x_dim=X_DIM, 
                       h_dim=H_DIM,
                       y_dim=Y_DIM,
                       time_steps=TIME_STEPS, 
                       act=lstm.sigmoid, 
                       act_p=lstm.sigmoid_p)


xs = [np.ones([1, X_DIM]) for t in TS]
ts = [.5 for t in TS]

state = np.ones([1, H_DIM])

def cost_fn(net):
    return 0.5 * np.sum([(net.out(t) - ts[t])**2.0 for t in TS])

LSTM Network version 0.3


In [12]:
key = 'o'


net.ff(xs, state, state)
print('net output: {}'.format([net.out(t) for t in TS]))

dys = [net.out(t) - ts[t] for t in TS]
print('dys: {}'.format(dys))

net.bp(dys, learning_rate=0.0)
print('analytic grad {}:\n{}'.format(key, net.grad[key]))

cost = cost_fn(net)

W = net.W[key].copy()
g = np.zeros_like(net.W[key])

h = 0.00001
for r in range(W.shape[0]):
    for c in range(W.shape[1]):
        net.W[key] = W.copy()
        net.W[key][r, c] += h

        net.ff(xs, state, state)

        cost2 = cost_fn(net)
        
        diff = (cost2 - cost)/h
        g[r, c] = diff

print('numerical grad {}:\n{}\n'.format(key, g))

net output: [array([[ 0.49011056]]), array([[ 0.54458724]])]
dys: [array([[-0.00988944]]), array([[ 0.04458724]])]
analytic grad o:
[[-0.00001476  0.00034163  0.00009647]
 [ 0.00001056  0.00005411  0.00008373]
 [-0.00000949  0.00028179  0.00009382]
 [ 0.00002954 -0.00016141  0.00007419]
 [ 0.00002954 -0.00016141  0.00007419]
 [ 0.00002954 -0.00016141  0.00007419]]
numerical grad o:
[[-0.00001476  0.00034163  0.00009647]
 [ 0.00001056  0.00005411  0.00008373]
 [-0.00000949  0.00028179  0.00009382]
 [ 0.00002954 -0.00016141  0.00007419]
 [ 0.00002954 -0.00016141  0.00007419]
 [ 0.00002954 -0.00016141  0.00007419]]

