In [1]:
%matplotlib inline

In [2]:
from matplotlib import pyplot as plt
import numpy as np
from ipywidgets import interact
from IPython.display import clear_output

np.set_printoptions(suppress=True)

import lstm

In [3]:
X_DIM = 2
H_DIM = 3
Y_DIM = 1
TIME_STEPS = 1
TS = range(TIME_STEPS)

net = lstm.LSTMNetwork(x_dim=X_DIM, 
                       h_dim=H_DIM,
                       y_dim=Y_DIM,
                       time_steps=TIME_STEPS, 
                       act=lstm.sigmoid, 
                       act_p=lstm.sigmoid_p)


xs = [np.ones([1, X_DIM]) for t in TS]
ts = [.5 for t in TS]

state = np.zeros([1, H_DIM])

def cost_fn(net):
    return 0.5 * np.sum([(net.out(t) - ts[t])**2.0 for t in TS])

LSTM Network version 0.3


In [6]:
key = 'o'


net.ff(xs, state, state)
print('net output: {}'.format([net.out(t) for t in TS]))

dys = [net.out(t) - ts[t] for t in TS]
print('dys: {}'.format(dys))

net.bp(dys, learning_rate=0.0)
print('analytic grad:\n{}'.format(net.grad[key]))

cost = cost_fn(net)

W = net.W[key].copy()
g = np.zeros_like(net.W[key])

h = 0.00001
for r in range(W.shape[0]):
    for c in range(W.shape[1]):
        net.W[key] = W.copy()
        net.W[key][r, c] += h

        net.ff(xs, state, state)

        cost2 = cost_fn(net)
        
        diff = (cost2 - cost)/h
        g[r, c] = diff

print('numerical grad f:\n{}\n'.format(g))

net output: [array([[ 0.701285]])]
dys: [array([[ 0.201285]])]
analytic grad:
[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.02516692 -0.00457382 -0.00764122]
 [ 0.02516692 -0.00457382 -0.00764122]
 [ 0.02516692 -0.00457382 -0.00764122]]
numerical grad f:
[[ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.          0.          0.        ]
 [ 0.00124457 -0.00010491 -0.0002259 ]
 [ 0.00124457 -0.00010491 -0.0002259 ]
 [ 0.00124457 -0.00010491 -0.0002259 ]]

